FROM node:20-alpine AS build
ARG VITE_KL_HOST
ENV VITE_KL_HOST=${VITE_KL_HOST}
ARG VITE_KL_REALM
ENV VITE_KL_REALM=${VITE_KL_REALM}
ARG VITE_KL_CLIENT
ENV VITE_KL_CLIENT=${VITE_KL_CLIENT}
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN pwd
COPY . .
RUN npm run build

FROM --platform=linux/amd64 nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]